name: Pull Request Test Workflow

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
      - develop
      - feature/*
      - bugfix/*
      - hotfix/*

jobs:
  test:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}

      - name: Install Dependencies
        run: |
          npm ci

      - name: Setup Virtual Display (Xvfb)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb=2:21.1.12-1ubuntu1.2
          Xvfb :99 -screen 0 1024x768x24 &

      - name: Run Tests
        env:
          DISPLAY: :99
        run: |
          npm run compile && npm run test
